name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Restart Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BOT_SERVER_HOST }}
          username: ${{ secrets.BOT_SERVER_USERNAME }}
          key: ${{ secrets.BOT_SERVER_SSH_KEY }}
          script: |
            cd /home/music_stream
            docker-compose stop music_stream
            docker-compose pull music_stream
            docker-compose up -d

      - name: Send Discord notification
        run: |
          curl -s -X POST -H "Content-Type: application/json" \
            -d "{\"content\": \"@music_stream service updated! Listen on Youtube - https://www.youtube.com/@zynthar_official.\"}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
